package com.k00ntz.aoc2025

import org.junit.jupiter.api.Assertions.*
import org.junit.jupiter.api.Test

class Day7Test {
    val d = Day7()

    val input = Tachyon.parse(
        """.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
""".split("\n")
    )

    @Test
    fun part1() {
        assertEquals(21, d.part1(input))
    }

    @Test
    fun part2() {
        assertEquals(40L, d.part2(input))
    }

}